services:
  database:
    image: postgres:15.4
    command: -p ${DB_PORT}
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
  api:
    restart: unless-stopped
    build: .
    ports:
      - '$API_PORT:$API_PORT'
    depends_on:
      - database
