services:
  database:
    image: postgres:15.4
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - 3020:5432

  api:
    restart: unless-stopped
    build: .
    ports:
      - '${API_PORT}:${API_PORT}'
    depends_on:
      - database
